ALTER TABLE version CHANGE COLUMN required_1753_world_quest_template required_1760_world_xilium_strings bit;

INSERT INTO `ixilium_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES
(50076, 'Loading Item Texts...', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50077, '>> Loaded 0 item texts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50078, '>> Loaded %u item texts', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50079, 'Loading Creature Model Based Info Data...', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50080, '>> Loaded %u creature model based info', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50081, 'Loading Equipment templates...', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50082, '>> Loaded %u equipment template', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50083, 'Loading Creature templates...', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50084, '>> Loaded %u creature definitions', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50085, 'Loading SpellsScriptTarget...', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50086, '>> Loaded 0 SpellScriptTarget. DB table `spell_script_target` is empty.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50087, '>> Loaded %u Spell Script Targets', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50088, 'Loading ItemRequiredTarget...', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50089, '>> Loaded %u Item required targets', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50090, 'Loading Creature Reputation OnKill Data...', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50091, '>> Loaded %u creature award reputation definitions', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50092, 'Loading Points Of Interest Data...', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50093, '>> Loaded %u Points of Interest definitions', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50094, 'Loading Creature Data...', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50095, '>> Loaded %lu creatures', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50096, 'Loading Creature Linked Respawn...', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50097, '>> Loaded %u linked respawns', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50098, 'Loading pet levelup spells...', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50099, '>> Loaded %u pet levelup and default spells for %u families', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50100, 'Loading pet default spell additional to levelup spells...', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50101, '>> Loaded addition spells for %u pet spell data entries and %u summonable creature templates', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50102, 'Loading Creature Addon Data...', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50103, '>> Creature Addon Data loaded', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50104, 'Loading Creature Respawn Data...', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50105, '>> Loaded 0 creature respawn time.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50106, '>> Loaded %lu creature respawn times', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50107, 'Loading Gameobject Data...', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50108, '>> Loaded %lu gameobjects', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50109, 'Loading Gameobject Respawn Times...', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50110, '>> Loaded 0 gameobject respawn times.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(50111, '>> Loaded %lu gameobject respawn times', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);